FROM debian:bookworm-slim
LABEL stage=builder
USER root

ENV BINUTILS_VERSION="2.41.90"
ENV TARGET="aarch64-linux-gnu"
ENV PREFIX="/opt/cross"

WORKDIR /opt/binutils

RUN apt update && apt -y install xz-utils gcc g++ make
ADD "https://sourceware.org/pub/binutils/snapshots/binutils-${BINUTILS_VERSION}.tar.xz" binutils.tar.xz
RUN tar -xf binutils.tar.xz --strip-components=1
RUN ./configure --target="${TARGET}" --prefix="${PREFIX}" --disable-nls --disable-werror && \
    make -j 8 && make install

FROM alpine:3
USER root
# https://wiki.alpinelinux.org/wiki/Running_glibc_programs
RUN apk update && apk add gcompat && addgroup -S binutils && adduser -S binutils -G binutils
COPY --from=0 /opt/cross /opt/cross
USER binutils
ENV PATH="${PATH}:/opt/cross/bin"
