image := "aarch64-binutils:latest"
podman-binutils-cmd := "podman run --rm -v $(pwd):/usr/src/workdir -w /usr/src/workdir " + image

build-image:
    podman build -t {{image}} {{justfile_directory()}}
    podman image prune --force --filter label=stage=builder

check-image:
    podman image exists {{image}}

hello-world: check-image
    mkdir -p bin
    {{podman-binutils-cmd}} aarch64-linux-gnu-as -o bin/hello_world.o hello_world/main.S
    {{podman-binutils-cmd}} aarch64-linux-gnu-ld -nostdlib -o bin/hello_world bin/hello_world.o

clean:
    rm -rf bin
